### ISSUE TITLE
Add the ability to push other variables into some files

### ISSUE THREAD

**Issue by trixartem** [f0rmat1k/bemy#24]
Added `{{blockName}}` into the file of template then got `b-block-name`, but it isn't good for variables in js.
I needed to create some variables in templates `BBlockName = ...`.

**Comment by f0rmat1k** [comment]
@trixartem i don't understand fully. Do you need for transform block name `block-name` into `BlockName` in some templates?

**Comment by trixartem** [comment]
Yes. I need

**Comment by f0rmat1k** [comment]
@trixartem  i'm thinking about callback in .bemy.json
`"template": ["tmp/js-template.js", "function(){  }"]`, but it's looks strange..

**Comment by f0rmat1k** [comment]
@trixartem I guess, the better variant is to add hook instead of callback. Using:
`"template": ["tmp/js-template.js", "yourOwnTool {{filePath}}"]`,
, or
`"template": ["tmp/js-template.js", "node ~/path/to/your/hook.js {{filePath}}"]`.

So in hook you can read the file and do needed action. What are you thinking about it?

**Comment by trixartem** [comment]
@f0rmat1k I think it's good solution `"template": ["tmp/js-template.js", "node ~/path/to/your/hook.js {{filePath}}"]`

**Comment by f0rmat1k** [comment]
@trixartem but there may be a problem with `-o` key, because bemy doesn't know, when the hook will finish the work, to open the final file. I'l check it.

**Comment by f0rmat1k** [comment]
I've added it to 3.3.0. For correct work `-o` you should use synchronous calls only.
